### PR TITLE
#fzk09 Adds kubectx/kubens tools

### PR DESCRIPTION
**Pull request by mllehrer**
These tools are added manually because a stable Deb package has not been released. Note that this PR does not include the completion scripts.

### CODE REVIEW

**Comment by jwhitlark** [comment]
@k2n I asked her to do it that way.  I was uncomfortable with cloning it in the other manner.

**Comment by k2n** [comment]
@jwhitlark we already have the projects that are cloned from GitHub and included in `clojure-dev` binary. Would you elaborate why it makes you uncomfortable? I'd like to keep consistency and minimize the burden if possible.

**Comment by jwhitlark** [comment]
@Kenji Do the scripts lock to a sha, or just pull latest?  The idea of
pulling latest when building our tooling container was what bothered me.
If we've got a way around it, or don't mind the risk, then I'm fine with
it.

Would you point Mia at an example in our repo that you're happy with?

**Comment by k2n** [comment]
@jwhitlark Got it, then we can clone, check out a specific SHA/tag, and copy. In general, it is not good idea to commit artifacts and something we don't manage. @mllehrer would you update the logic accordingly?

**Comment by k2n** [comment]
@jwhitlark however, I don't agree with the policy that we should lock down everything in `docker-clojure-dev`. We have to pay attention and update the version from base image to all binaries included in this image, and I believe it's too much burden on us. I'd like to manage the dependency for applications strictly and eliminate any moving elements such as `SNAPSHOT`, but for tools, it may not be the bad idea to rely on the community, accept the latest whenever we rebuild this image, and rollback if we find some issues.

**Comment by mllehrer** [comment]
👍 will do, Kenji

**Comment by mllehrer** [comment]
@k2n I reached out to @jwhitlark yesterday to confirm that we were on the same page about not locking in dependencies. I just forgot to ask him to sign off on here 😅. Merging

**Pull request merged**
